### ISSUE TITLE
Manejo de los diferentes formatos para ingresar la fecha de los venue

### ISSUE THREAD

**Issue by brolin** [daquina-io/visualizacion_apariciones_proyectos_musicales#14]
Existen varios formatos para ingresar la fecha de los venue unos con hora, otros sin hora. El sistema debe ser capaz de procesar todas esta maneras.

**Comment by brolin** [comment]
Se resuelve creando la función normalizar_fecha que es capaz por ahora de procesar las fechas en formato AAAA-MM-DD y AAAA-MM-DD hh:mm:ss Si no están las fechas de acuerdo a estos formatos las "parsea" mal.

Se resuelve temporalmente con el commit https://github.com/daquina-io/visualizacion_apariciones_proyectos_musicales/commit/deafd98e2f9e0360f56f44e85a9133a882dc31d4

Se retira la dependencia de las funciones que generan las gráficas de parsear la columna Date como fecha

```
normalizar_fecha <- function(flatten_data_date) {
    tmp_date <- flatten_data_date
    flatten_data_date <- ymd(flatten_data_date)
    flatten_data_date[which(is.na(flatten_data_date))] <- ymd_hms(tmp_date[which(is.na(flatten_data_date))])
    flatten_data_date
}
```

**Comment by son0p** [comment]
Venimos ingresando según el formato de Bands in Town con la letra "T"en el medio de la fecha y el tiempo 
AAAA-MM-DDThh:mm:ss  esto haría que no "parsee"?

**Comment by brolin** [comment]
¿Cuál grupo tiene datos con fechas en este formato? Yo creo que lo "parsea" bien

**Comment by son0p** [comment]
Lo probé con fonseca que tiene ambos tipos de fecha y funciona muy bien!  felicitaciones!
