### ISSUE TITLE
Agregar una descripción a la aplicación de Shiny 

### ISSUE THREAD

**Issue by brolin** [daquina-io/visualizacion_apariciones_proyectos_musicales#5]
Agregar una descripción de lo que estamos haciendo y cómo lo estamos haciendo en la página de shiny. Agregar un enlace al repositorio donde está la información

**Comment by son0p** [comment]
resuelto en commit [ b5e2f73  ](https://github.com/daquina-io/visualizacion_apariciones_proyectos_musicales/commit/b5e2f73e7dbda2a31e4f7e6e223036c241ae2e39)
