### ISSUE TITLE
Redireccionar deploy viejo al nuevo

### ISSUE THREAD

**Issue by son0p** [daquina-io/visualizacion_apariciones_proyectos_musicales#6]
Quizá modificando la aplicación vieja para que redireccione a la nueva .. o en el caso que no se pueda poner el link con algún texto que diga "la versión actualizada de este sitio esta acá"

**Comment by brolin** [comment]
Se cierra el sitio con la url https://daquina.shinyapps.io/ShinyAparicionesGrupos/ el definitivo es https://daquina.shinyapps.io/visualizacion_apariciones_grupos/
